[tool.poetry]
name = "Choral-Quartets-F0-Extractor"
version = "0.3.0"
description = "An application that uses Multi-Pitch Estimation and Voice Assignment to transform audio files with Choral Quartets recordings into files (CSV, HDF5 and MIDI) containing F0 estimations for each voice (Soprano, Alto, Tenor and Bass)."
authors = ["André Paiva (Xornotor) <andre.paiva@ufba.br>"]
license = "cc"
readme = "README.md"
packages = [{include = "Choral_Quartets_F0_Extractor"}]

[tool.poetry.dependencies]
python = "^3.11"
tensorflow = "^2.14"
gradio = "^6.7"
typing-extensions = "^4.15"
mido = "^1.3.3"
pumpp = "^0.6"
numpy = "^1.26"
scipy = "^1.14"
pandas = "^2.2"
hdf5plugin = "^4.4"
h5py = "^3.9"
tables = "^3.9"
librosa = "^0.10"
matplotlib = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
