name: Hugging Face
on:
  workflow_run:
    workflows: ["Gradio App Test"]
    branches: [main]
    types:
      - completed

jobs:
  sync:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Sync to Hugging Face Hub
        uses: huggingface/hub-sync@v0.2.1
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: Xornotor/Choral-Quartets-F0-Extractor
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          subdirectory: "app"
