name: Gradio App Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Code Checkout
      uses: actions/checkout@v4

    - name: Setting up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y libsndfile1
        python -m pip install --upgrade pip
        pip install pytest pytest-mock
        pip install -r app/requirements.txt

    - name: Run API Tests
      run: |
        pytest app/test.py -v --tb=short --log-cli-level=INFO
